// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADJ46roReDtO1X73m-wxjuW0YGeHfdKz8',
    appId: '1:437242870519:web:38cc24d5d3cb49b4ee31f2',
    messagingSenderId: '437242870519',
    projectId: 'kangaroocare-aabad',
    authDomain: 'kangaroocare-aabad.firebaseapp.com',
    databaseURL: 'https://kangaroocare-aabad-default-rtdb.firebaseio.com',
    storageBucket: 'kangaroocare-aabad.appspot.com',
    measurementId: 'G-9JWXNYRFHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnJw905737JNqTkQXguBSz6AOZPbxC5Y',
    appId: '1:437242870519:android:e9ee13d7564414beee31f2',
    messagingSenderId: '437242870519',
    projectId: 'kangaroocare-aabad',
    databaseURL: 'https://kangaroocare-aabad-default-rtdb.firebaseio.com',
    storageBucket: 'kangaroocare-aabad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQiZzJPsbhGti2EmR2XhwZ5c_8alBy0Bo',
    appId: '1:437242870519:ios:e9b9a6143da504d3ee31f2',
    messagingSenderId: '437242870519',
    projectId: 'kangaroocare-aabad',
    databaseURL: 'https://kangaroocare-aabad-default-rtdb.firebaseio.com',
    storageBucket: 'kangaroocare-aabad.appspot.com',
    iosBundleId: 'com.example.kangaroocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQiZzJPsbhGti2EmR2XhwZ5c_8alBy0Bo',
    appId: '1:437242870519:ios:c61cd8c3591c1fcdee31f2',
    messagingSenderId: '437242870519',
    projectId: 'kangaroocare-aabad',
    databaseURL: 'https://kangaroocare-aabad-default-rtdb.firebaseio.com',
    storageBucket: 'kangaroocare-aabad.appspot.com',
    iosBundleId: 'com.example.kangaroocare.RunnerTests',
  );
}
